### ISSUE TITLE
유저 스탯 api 구현

### ISSUE THREAD

**Issue by gsh118** [MTV4-Project4/be_repo#12]
## 🚀 Description
유저 인벤토리 관리 도메인 엔티티 구현 및 crud 용 api 구현

## ✅ TODO
- [x] 유저 스탯 domain 구현
- [x] 유저 스탯 cud 서비스 구현
- [x] 유저 스탯 조회용 sql 쿼리 작성
- [x] 유저 스탯 crud용 api 컨트롤러 작성
