### ISSUE TITLE
파일 업로드 및 자세 유사도 챌린지

### ISSUE THREAD

**Issue by gsh118** [MTV4-Project4/be_repo#19]
## 🚀 Description
파일 업로드 및 자세 유사도 챌린지

## ✅ TODO
- [x] S3환경 구축 및 파일 업로드 코드 작성 
- [x] 자세 유사도 챌린지 db 및 api 구현
- [x] 유저 참가 정보 db및 api 구현
