### ISSUE TITLE
간단한 로그인 기능 추가 및 로그 수집 기능 추가 예정

### ISSUE THREAD

**Issue by gsh118** [MTV4-Project4/be_repo#24]
## 🚀 Description
시간 문제로 일반적인 로그인 형태보단 간단하게 비밀번호 암호화만 되는 수준으로 추가 예정
(베타 이후 보완 가능성 있음)

## ✅ TODO
- [x] 로그인 기능 추가
- [x] rest controller를 이용한 로그 관리 기능 추가
- [x] 출력과 파일 저장 로그 형태 분리
